name: flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  http: ^0.13.4
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^2.5.1
  firebase_auth: ^1.1.1
  firebase_core: ^1.6.0
  google_fonts: ^2.0.0
  provider: ^5.0.0
  fluttertoast: ^8.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - graphics/
